import java.util.List;
import java.util.ArrayList;



/**
 *
 * @author student
 */
public class StudentGrades extends javax.swing.JFrame {
    // Creates list that stores objects
    List students = new ArrayList<StudentGradesJava>();
    // Variables for first and last name 
    String FirstName = "";
    String LastName = "";
      
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TitleName = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameInput = new javax.swing.JTextField();
        Test1Label = new javax.swing.JLabel();
        Test2Label = new javax.swing.JLabel();
        TestTwoInput = new javax.swing.JTextField();
        Test3Label = new javax.swing.JLabel();
        TestOneInput = new javax.swing.JTextField();
        TestThreeInput = new javax.swing.JTextField();
        Test4Label = new javax.swing.JLabel();
        TestFourInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        LastNameInput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        ListButton = new javax.swing.JButton();
        StudentAverage = new javax.swing.JButton();
        CourseAverage = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputMessage = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleName.setText("Student Grades Calculator");

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstNameLabel.setText("First Name:");

        Test1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Test1Label.setText("Test 1:");

        Test2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Test2Label.setText("Test 2:");

        Test3Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Test3Label.setText("Test 3:");

        Test4Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Test4Label.setText("Test 4:");

        LastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name:");

        AddButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ListButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListButton.setText("List");
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });

        StudentAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StudentAverage.setText("Student Average");
        StudentAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAverageActionPerformed(evt);
            }
        });

        CourseAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseAverage.setText("Course Average");
        CourseAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseAverageActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        OutputMessage.setColumns(20);
        OutputMessage.setRows(5);
        jScrollPane1.setViewportView(OutputMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleName, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Test4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TestFourInput, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Test3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TestThreeInput))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Test2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Test1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TestTwoInput)
                                    .addComponent(FirstNameInput)
                                    .addComponent(TestOneInput, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LastNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ListButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StudentAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CourseAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestOneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Test1Label)
                    .addComponent(AddButton)
                    .addComponent(StudentAverage))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TestTwoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ListButton)
                        .addComponent(CourseAverage))
                    .addComponent(Test2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestThreeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestFourInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        // Gets first name, last name, and mark variables from user
        FirstName = FirstNameInput.getText();
        LastName = LastNameInput.getText();
        float mark1 = Float.parseFloat(TestOneInput.getText());
        float mark2 = Float.parseFloat(TestTwoInput.getText());
        float mark3 = Float.parseFloat(TestThreeInput.getText());
        float mark4 = Float.parseFloat(TestFourInput.getText());
        
        // Creates the object 
        StudentGradesJava st1 = new StudentGradesJava(FirstName,LastName,mark1,mark2,mark3,mark4);
        
        // Adds the object to a list everytime you add another student     
        students.add(st1);
        
        // Outputs the student info that user added
        OutputMessage.setText(st1.toString());
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButtonActionPerformed
        // TODO add your handling code here:
        
        // Outputs sentence above the list
        OutputMessage.setText("First Name\tLast Name\tMark1\tMark2\tMark3\tMark4\n");
        
        // For loop that prints it all in the list 
        for (int counter = 0; counter < students.size(); counter++)  {
            OutputMessage.append(students.get(counter).toString() + "\n");
        }
    }//GEN-LAST:event_ListButtonActionPerformed

    private void CourseAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseAverageActionPerformed
        // TODO add your handling code here:
        
        // Creates the course average variable 
        float CourseAverage = 0;
        
        // Gets size of student list and calculates the average of each student in the list 
        for (int i =0; i<students.size(); i++){
            StudentGradesJava st1 = (StudentGradesJava) students.get(i);
            // Adds all of the course averages together 
            CourseAverage+=st1.getAverage();
        }
        
        // Divides the CourseAverage by the number of students in the list
        CourseAverage = CourseAverage/students.size();
        
        // Prints course average
        OutputMessage.setText("Course Average: "+CourseAverage+"% \n");
    }//GEN-LAST:event_CourseAverageActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        
        // Exit closes when pressed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void StudentAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAverageActionPerformed
        // TODO add your handling code here:
        
        // Gets the first and last name variables
        FirstName = FirstNameInput.getText();
        LastName = LastNameInput.getText();
        
        // Gets the average for the currently entered student, program will not run if the student is not in the list
        // Then prints the students 
        for (int i = 0; i<students.size(); i++) {
            StudentGradesJava st1 =(StudentGradesJava) students.get(i);
        if (st1.getFirstName().equals(FirstName)){
            if (st1.getLastName().equals(LastName)){
                float StudentAverage = st1.getAverage();
                OutputMessage.setText(FirstName+"  "+LastName+": "+StudentAverage+"% \n");
            }
        }
        }
       
      
    }//GEN-LAST:event_StudentAverageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CourseAverage;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton ListButton;
    private javax.swing.JTextArea OutputMessage;
    private javax.swing.JButton StudentAverage;
    private javax.swing.JLabel Test1Label;
    private javax.swing.JLabel Test2Label;
    private javax.swing.JLabel Test3Label;
    private javax.swing.JLabel Test4Label;
    private javax.swing.JTextField TestFourInput;
    private javax.swing.JTextField TestOneInput;
    private javax.swing.JTextField TestThreeInput;
    private javax.swing.JTextField TestTwoInput;
    private javax.swing.JLabel TitleName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
